language: node_js
node_js:
  - v20.13.1
env:
  matrix:
    - NODE_OPTIONS="--max-old-space-size=4196"
cache:
  directories:
    - node_modules
install:
  - npm install
before_install:
  - npm i -g npm@10.5.2
script:
  - npm run test:ci
